### ISSUE TITLE
estat: too many arguments output when there are too few

### ISSUE THREAD

**Issue by sebroy** [delphix/performance-diagnostics#14]
When I forget to include a duration at the end, I get:
```
delphix@guild:~$ sudo estat backend-io -lz
/usr/bin/estat: Too many arguments
```
I also find it confusing that the mandatory duration argument doesn't show up in the usage. We should also display the usage on errors like the above.

**Comment by jgallag88** [comment]
Thanks for catching this. The fix is included in #9.

> I also find it confusing that the mandatory duration argument doesn't show up in the usage.

The duration is shown in the usage, but for the subcommand, since it isn't accepted by every subcommand.

> We should also display the usage on errors like the above.

I had avoided this because the full help message is pretty long, and I find it gets a bit annoying when you mistype something and a command fills your whole terminal with a big usage message. I guess maybe we could show a brief top-level usage message or a brief subcommand one, depending on the context. I'm open to other ideas though.

**Comment by sebroy** [comment]
> The duration is shown in the usage, but for the subcommand, since it isn't accepted by every subcommand.

Ah, I see that now. Looking at the usage for `zil`, I do find it arbitrary that it doesn't take a duration argument. That would make things a lot simpler...

**Comment by prashks** [comment]
Maybe we could set duration to a default value if not given via the command line

**Comment by sebroy** [comment]
@prashks I like that idea, and it also removes one of my biggest command-line syntax pet peeves from this command, which is positional arguments. I think we should just make the duration an optional command-line flag that takes an argument, removing the mandatory final positional argument.

**Comment by sebroy** [comment]
I've separated out the above request into its own issue so that @jgallag88 can move forward with fixing the primary problem stated in this issue. See https://github.com/delphix/performance-diagnostics/issues/16 for issues with the `duration` argument.

**Comment by prashks** [comment]
> 
> I had avoided this because the full help message is pretty long, and I find it gets a bit annoying when you mistype something and a command fills your whole terminal with a big usage message. I guess maybe we could show a brief top-level usage message or a brief subcommand one, depending on the context. I'm open to other ideas though.

Yeah showing a brief usage message sounds good (like our internal `dc` command), 
the brief message could be just something like:

```
USAGE:  estat [-h]
        estat [prog] [options]
```

and the detailed usage can be shown when the user chooses `estat -h` invocation...
